# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170626_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='ctime',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.UserGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(error_messages={'required': '请输入密码'}, max_length=64),
        ),
    ]
